easy_admin:
    entities:
        User:
            class: App\Entity\User
            list:
                fields:
                    - id
                    - username
                    - email
            form:
                fields:
                    - username
                    - email
                    - password

    design:
        templates:
            - 'admin/my-dashboard.html.twig'
